name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip3 install black
        sudo apt-get install tidy -y
        wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb
        sudo dpkg -i tidy-5.4.0-64bit.deb

    - name: Run linters
      run: |
        ./check_links.py
        ./format.py
        ./gen_id_attributes.py
        ./sitemap.py

    - name: Verify linters made no changes
      run: git --no-pager diff --exit-code HEAD
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          texlive-generic-extra \
          texlive-latex-extra \
          latexmk

    - name: Generate figures
      run: |
        cd ci/state-machines/state-machine/state-diagram && (./make.sh || true)

    - name: Verify state-diagram.png was generated
      run: test -f ci/state-machines/state-machine/state-diagram/state-diagram.png
