name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install black requests
        #sudo apt-get install tidy -y

    - name: Install tidy
      run: |
        git clone git://github.com/htacg/tidy-html5
        cd tidy-html5/build/cmake
        cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=DEB
        make package -j$(nproc)
        sudo dpkg -i tidy-5.7.28-64bit.deb
        cd ../../..
        rm -r tidy-html5

    - name: Check links
      run: python3 check_links.py

    - name: Run formatter
      run: python3 format.py

    - name: Generate ID attributes
      run: python3 gen_id_attributes.py

    - name: Generate sitemap
      run: python3 sitemap.py

    - name: Verify linters made no changes
      run: git --no-pager diff --exit-code HEAD
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          texlive-generic-extra \
          texlive-latex-extra \
          latexmk

    - name: Generate figures
      run: |
        cd ci/state-machines/state-machine/state-diagram && (./make.sh || true)

    - name: Verify state-diagram.png was generated
      run: test -f ci/state-machines/state-machine/state-diagram/state-diagram.png
